version: '3'
services:
  flask:
    build:
      context: app
      dockerfile: Dockerfile
    container_name: flask
    image: digitalocean.com/flask-python:3.6
    restart: unless-stopped
    environment:
      APP_ENV: "dev"
      APP_DEBUG: "True"
      APP_PORT: 5000
      MONGODB_DATABASE: flaskdb
      MONGODB_USERNAME: flaskuser
      MONGODB_PASSWORD: flaskpwd
      MONGODB_HOSTNAME: mongodb
    volumes:
      - ./app:/var/www
    ports:
    - 5000:5000
    depends_on:
      - mongodb
    networks:
      - frontend
      - backend
  mongodb:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    command: mongod --auth
    environment:
      MONGO_INITDB_DATABASE: flaskdb
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongopwd
      MONGO_NON_ROOT_USERNAME: flaskuser
      MONGO_NON_ROOT_PASSWORD: flaskpwd
      $MONGO_NON_ROOT_ROLE: readWrite
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - ./docker/mongo/00_setup_user.sh:/docker-entrypoint-initdb.d/00_setup_user.sh:ro
      - ./docker/mongo/init.js:/docker-entrypoint-initdb.d/init.js:ro
      - mongodbdata:/data/db
    networks:
      - backend
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    networks:
      - backend
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongoadmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongopwd
      ME_CONFIG_MONGODB_SERVER: mongodb
volumes:
  mongodbdata:
    driver: local
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge