version: '3'
services:
  flask:
    restart: always
    volumes:
      - appdata:/app
    ports:
    - ${APP_PORT}:5000
    depends_on:
      - mongodb
  mongodb:
    restart: always
  mongo-express:
    restart: always

volumes:
  appdata:
    driver: local
